# Generated by Django 4.2.7 on 2023-11-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_type", models.CharField(blank=True, max_length=200, null=True)),
                ("sold_date", models.DateField()),
            ],
        ),
    ]
