# Generated by Django 4.2.7 on 2023-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapi", "0002_data_address_data_baths_data_beds_data_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="sold_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="data",
            name="year_built",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
