# Generated by Django 4.2.7 on 2023-11-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demoapi", "0003_alter_data_sold_date_alter_data_year_built"),
    ]

    operations = [
        migrations.RenameField(
            model_name="data",
            old_name="longtitude",
            new_name="longitude",
        ),
    ]
