# Generated by Django 4.2.7 on 2023-11-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapi", "0004_rename_longtitude_data_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="next_open_house_end_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="data",
            name="next_open_house_start_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
