# Generated by Django 4.2.7 on 2023-11-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapi", "0005_alter_data_latitude_alter_data_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="baths",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="sold_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
